apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: backend-tests-go-eztbvwiq
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/backend-tests-go-eztbvwiq:b93c206f2329548fcb50ca0724d715c188707c83
          name: container-image
